[package]
name = "Assigment1"
version = "0.1.0"
authors = ["Farhan Aziz <farhanazizumrani95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
